#@data/values-schema
---

#@schema/desc "Logging configuration."
logging:
  #@schema/desc "The Operator log level. Valid options are `info` and `debug`."
  #@schema/validation one_of=["info", "debug"]
  level: info

#@schema/desc "Settings for Prometheus metrics."
prometheus:
  #@schema/desc "Whether to enable Prometheus annotations for automatic scraping of RabbitMQ Operator metrics."
  enabled: true
